export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCEESS = 'CREATE_USER_SUCCEESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const CREATE_DB_USER_REQUEST = 'CREATE_DB_USER_REQUEST';
export const CREATE_DB_USER_SUCCEESS = 'CREATE_DB_USER_SUCCEESS';
export const CREATE_DB_USER_FAILURE = 'CREATE_DB_USER_FAILURE';

export const UPDATE_DB_USER_REQUEST = 'UPDATE_DB_USER_REQUEST';
export const UPDATE_DB_USER_SUCCEESS = 'UPDATE_DB_USER_SUCCEESS';
export const UPDATE_DB_USER_FAILURE = 'UPDATE_DB_USER_FAILURE';

export const DELETE_DB_USER_REQUEST = 'DELETE_DB_USER_REQUEST';
export const DELETE_DB_USER_SUCCEESS = 'DELETE_DB_USER_SUCCEESS';
export const DELETE_DB_USER_FAILURE = 'DELETE_DB_USER_FAILURE';

export const SEND_EMAIL_INVITATION_REQUEST = 'SEND_EMAIL_INVITATION_REQUEST';
export const SEND_EMAIL_INVITATION_SUCCESS = 'SEND_EMAIL_INVITATION_SUCCESS';
export const SEND_EMAIL_INVITATION_FAILURE = 'SEND_EMAIL_INVITATION_FAILURE';