export const FULL_LOGIN_REQUEST = 'FULL_LOGIN_REQUEST';
export const FULL_LOGIN_SUCCESS = 'FULL_LOGIN_SUCCESS';
export const FULL_LOGIN_FAILURE = 'FULL_LOGIN_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const TWITTER_LOGIN_REQUEST = 'TWITTER_LOGIN_REQUEST';
export const TWITTER_LOGIN_SUCCESS = 'TWITTER_LOGIN_SUCCESS';
export const TWITTER_LOGIN_FAILURE = 'TWITTER_LOGIN_FAILURE';

export const GITHUB_LOGIN_REQUEST = 'GITHUB_LOGIN_REQUEST';
export const GITHUB_LOGIN_SUCCESS = 'GITHUB_LOGIN_SUCCESS';
export const GITHUB_LOGIN_FAILURE = 'GITHUB_LOGIN_FAILURE';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const VALIDATE_EMAIL_REQUEST = 'VALIDATE_EMAIL_REQUEST';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';
export const VALIDATE_EMAIL_FAILURE = 'VALIDATE_EMAIL_FAILURE';

export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILURE = 'REFRESH_TOKEN_FAILURE';

export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const DISABLE_ACCOUNT_REQUEST = 'DISABLE_ACCOUNT_REQUEST';
export const DISABLE_ACCOUNT_SUCCESS = 'DISABLE_ACCOUNT_SUCCESS';
export const DISABLE_ACCOUNT_FAILURE = 'DISABLE_ACCOUNT_FAILURE';


export const SIGN_IN_WITH_EMAIL_REQUEST = 'SIGN_IN_WITH_EMAIL_REQUEST';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_FAILURE = 'SIGN_IN_WITH_EMAIL_FAILURE';

export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
