export const GET_MEALS_REQUEST = 'GET_MEALS_REQUEST';
export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_FAILURE = 'GET_MEALS_FAILURE';

export const ADD_MEAL_REQUEST = 'ADD_MEAL_REQUEST';
export const ADD_MEAL_SUCCESS = 'ADD_MEAL_SUCCESS';
export const ADD_MEAL_FAILURE = 'ADD_MEAL_FAILURE';

export const DELETE_MEAL_REQUEST = 'DELETE_MEAL_REQUEST';
export const DELETE_MEAL_SUCCESS = 'DELETE_MEAL_SUCCESS';
export const DELETE_MEAL_FAILURE = 'DELETE_MEAL_FAILURE';

export const EDIT_MEAL_REQUEST = 'EDIT_MEAL_REQUEST';
export const EDIT_MEAL_SUCCESS = 'EDIT_MEAL_SUCCESS';
export const EDIT_MEAL_FAILURE = 'EDIT_MEAL_FAILURE';

export const GET_MEAL_CALORIES_REQUEST = 'GET_MEAL_CALORIES_REQUEST';
export const GET_MEAL_CALORIES_SUCCESS = 'GET_MEAL_CALORIES_SUCCESS';
export const GET_MEAL_CALORIES_FAILURE = 'GET_MEAL_CALORIES_FAILURE';

export const GET_ALL_MEALS_REQUEST = 'GET_ALL_MEALS_REQUEST';
export const GET_ALL_MEALS_SUCCESS = 'GET_ALL_MEALS_SUCCESS';
export const GET_ALL_MEALS_FAILURE = 'GET_ALL_MEALS_FAILURE';